name: CI + CD with Canary Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Java CI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests
        run: mvn clean test

  deploy-staging:
    name: Deploy to Heroku Staging
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: mvn clean package -DskipTests

      - name: Deploy to Heroku Staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote add staging https://heroku:${HEROKU_API_KEY}@git.heroku.com/my-java-app-staging.git
          git push staging HEAD:main


  deploy-canary:
    name: Deploy to Heroku Canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: mvn clean package -DskipTests

      - name: Deploy to Canary
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote add canary https://heroku:${HEROKU_API_KEY}@git.heroku.com/my-java-app-canary.git
          git push canary HEAD:main

  deploy-production:
    name: Promote to Full Production
    needs: deploy-canary
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Full Production
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote add prod https://heroku:${HEROKU_API_KEY}@git.heroku.com/my-java-app.git
          git push prod HEAD:main
