name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Build and Test Java App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test with Maven
        run: mvn clean verify

  deploy-staging:
    name: Deploy to Heroku Staging
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Heroku Staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add staging https://heroku:${HEROKU_API_KEY}@git.heroku.com/my-java-app-staging.git
          git push staging HEAD:main --force

  deploy-production:
    name: Deploy to Heroku Production
    needs: deploy-staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Heroku Production
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add prod https://heroku:${HEROKU_API_KEY}@git.heroku.com/my-java-app-prod.git
          git push prod HEAD:main --force
